# Generated by Django 5.1.1 on 2024-10-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='additional_ingredients',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='removed_ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_print',
            field=models.TextField(blank=True, null=True),
        ),
    ]
