# Generated by Django 5.1.1 on 2024-10-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_orderitem_additional_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='actual_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
