# Generated by Django 5.1.1 on 2024-10-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_orderitem_actual_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='num_left',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
