# Generated by Django 5.1.1 on 2024-10-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_menuitem_num_left_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='modified_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
